services:
  app:
    build: ./rmd-inventory-backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=rmd_inventory
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - APP_URL=http://localhost:8000
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build: ./rmd-inventory-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: npm run dev -- --host --port 3000
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=rmd_inventory
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge